# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23cf7c3013dacd8a3c8b99d4171c4290c8c5483615890c44094d42577e4d61a3d3733bb089d74322476b273750b901b759f2f59170006af7004c03c3ab98017a

test:
  secret_key_base: c7c57029b03deb38fbd3207c4f509b8c4308b28f9a953e2aba5db43afbcc49748dd1e9696276baebaee3e4280b08d1e63e85a31db11a2c52b67ccc4e4725b588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
